### PR TITLE
Compatibility with up to macOS 11.4

### PR DESCRIPTION
**Pull request by barijaona**
This automates the trick described in #133 and #134:
- adds UUIDs
- the installer applies system policy allowing Apple's Mail to enable the plugin

### CODE REVIEW

**Comment by barijaona** [comment]
NB: supersedes #119

**Comment by caban13** [comment]
hi
i am user, i don't know were to add the part of "[Compatibility with up to macOS 11.4](https://github.com/UniversalMailer/UniversalMailer/pull/137/commits/eddd819941ad36f8e59ea4b7ec89c532a077b939)"
thanks
alain

**Comment by barijaona** [comment]
As @UniversalMailer (initial author) has apparently ended support, I will publish a binary including my changes this weekend.

**Comment by barijaona** [comment]
This build includes my patches : 

https://github.com/barijaona/UniversalMailer/releases/tag/v%2F3.0.1

**Comment by barijaona** [comment]
Closing this, as up to date fork is now available at https://github.com/barijaona/UniversalMailer/releases/latest

**Pull request closed without merging**
